var language = {
    "en":{
        "Home":"Home",
        "About":"About",
        "Usage":"Usage",
        "Document":"Document",
        "AddNewBlock":"Add New Block",
        "GeneratePassword":"GENERATE PASSWORD",
        "holder-BlockName":"Block Name",
        "keyword":"KEYWORD",
        "holder-answer":"a familiar keyword",
        "AddNewKeyword": "Add new KEYWORD",
        "RemoveLastKeyword":"Remove Last KEYWORD",
        "GenPassword":"Generate Password",
        "NoOfChar":"Number of characters:",
        "InvalidNoOfCharWarning":"Invalid Number of characters. Number of characters must be between 6 and 32",
        "YourPassword":"Your Password:",
        "holder-DisplayPassword":"Your Password displayed here",
        "Hint":"Hint",
        "holder-hint":"The hint for your keyword",
        "AddNewHint":"Add New Hint",
        "SubmitNewBlock":"Submit Block",
        "waiting":"Waiting",
        "SubmitNewBlockSuccess":"Submit New Block Successfull!",
        "language":"English",
        "BlockName":"BLOCK NAME",
        "blockname":"Block name:",
        "footer-description-1" : "High secured password from easy to remember keywords",
        "copyleft-1": "Developed by :",
        "copyleft-2": "Design by: ",
        "Powered-By": "Powered by ",
        "html-content": 
        'There are a lot of websites and applications, for example, email, favourite forums or social networks having password authentication. <br />' + '                Most of the cases, the passwords are the same or nearly the same among the websites with a unique login account.<br />' + '                There is a security risk if the above situation is occured, only one leaked password is needed to <i>hack</i> all the accounts on these website. <br />' + '            <br />' + '                Thus, <a href="../">easykeytopass</a> is used to organize and memorize all your passwords with a block of <b>HINT(S)</b> and <b>KEYWORD(S)</b>. <br />' + '' + '                In short, a constant password is generated after input the correct <b>BLOCK NAME</b> and <b>KEYWORDS</b> for each hints.<br />' + '                <br />' + '                <br />' + '                About us: <br />' + '                We have faced the issue that <b>"one password for all"</b>. <br />' + '                If the password is disclosed, there are tons of thing need to be change. <br />' + '                <br />' + '                With keyword-based password, the only thing we need to remember are the <b>BLOCK NAME</b> and the answers for listed hint(s).<br />'
    },
    "vi":{
        "Home":"Trang chủ",
        "About":"Giới thiệu",
        "Usage":"Hướng dẫn",
        "Document":"Tài liệu",
        "AddNewBlock":"Thêm Khối Mới",
        "GeneratePassword":"TẠO MẬT KHẨU",
        "holder-BlockName":"Tên Khối",
        "keyword":"Từ khóa",
        "holder-answer":"Từ khóa quen thuộc",
        "AddNewKeyword": "Thêm từ khóa",
        "RemoveLastKeyword":"Xóa từ khóa",
        "GenPassword":"Tạo mật khẩu",
        "NoOfChar":"Chiều dài chuỗi mật khẩu:",
        "InvalidNoOfCharWarning":"Chiều dài chuỗi mật khẩu là một số từ 6 đến 32",
        "YourPassword":"Mật Khẩu của bạn:",
        "holder-DisplayPassword":"Mật khẩu sẽ được hiện thị tại đây",
        "Hint":"Gợi ý",
        "holder-hint":"Gợi ý cho từ khóa",
        "AddNewHint":"Thêm gợi ý",
        "SubmitNewBlock":"Lưu Khối",
        "waiting":"Đang chờ phải hồi từ máy chủ",
        "SubmitNewBlockSuccess":"Thêm Khối mới thành công!",
        "language":"Tiếng Việt",        
        "BlockName":"TÊN KHỐI",
        "blockname":"Tên khối:",
        "footer-description-1": "Mật khẩu bảo mật cao từ những từ khóa dễ nhớ",
        "copyleft-1": "Phát triển bởi:",
        "copyleft-2": "Thiết kế bởi: ",
        "Powered-By": "Được hỗ trợ từ ",
        "html-content": 
        'Rất nhiều trang web và ứng dụng cần mật khẩu để xác thực. <br />' + 'Hầu hết các trường hợp mật khẩu được dùng chung giữa các trang web và ứng dụng đó với cùng một tài khoản.<br />' + 'Với trường hợp trên, chỉ với một mật khẩu bị lộ, tất cả các tài khoản khác trên những trang web hoặc ứng dụng khác có nguy cơ bị đánh cắp cao. <br />' + '<br />' + '               Vì vậy, <a href="../">easykeytopass</a> được dùng để tổ chức mật khẩu dưới dạng dễ nhớ với <b>CÁC TỪ GỢI Ý </b> và <b>TỪ KHÓA</b>. <br />' + 'Tóm lại, một mật khẩu cố định luôn được tạo ra sau khi nhập <b>TÊN TẬP HỢP CÁC GỢI Ý</b> và <b>TỪ KHÓA</b> cho mỗi gợi ý cho trước, nếu có.<br />' + '<br />' + '<br />' + ' Về chúng tôi: <br />' + '                Chúng tôi cảm thấy <b>dùng chung mật khẩu cho nhiều thứ</b> tiềm ẩn nguy cơ bị ăn trộm thông tin cá nhân. <br />' + 'Chỉ cần một trang web hoặc ứng dụng để lộ thông tin mật khẩu, thì lại phải đổi tất cả mật khẩu trên các trang khác. <br />' + '<br />' + 'Vơi mật khẩu dựa trên từ khóa, chúng tôi chỉ cần nhớ hai thứ duy nhất đó là  <b>TÊN TẬP HỢP CÁC GỢI Ý</b> và trả lời các gợi ý được liệt kê trong đó.<br />'
    }
}